In [23]:
import pandas as pd

# Cargar CSV
df = pd.read_excel('animales_filtrados.xlsx')

# Normalizar columnas
df.columns = df.columns.str.lower().str.replace(' ', '_')

# Ver las primeras filas
df.head(10)

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion,causa_amenaza,tipo_habitat
0,Myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
1,Alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
2,Amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
3,Ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
4,Ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
5,Australoheros facetus,Chanchito,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
6,Branta canadensis,Barnacla canadiense grande,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
7,Threskiornis aethiopicus,Ibis sagrado,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
8,Esox lucius,Lucio,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
9,Fundulus heteroclitus,Fúndulo,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN

In [24]:
# Lista de grupos que NO son animales
no_animales = ['planta','plantas vasculares','hongos','briofitos','flora','algas','cromistas y bacterias']

# Filtrar solo animales
df_animales = df[~df['grupo'].str.lower().isin(no_animales)]

# Quitar filas sin nombre científico
df_animales = df_animales.dropna(subset=['nombre_cientifico'])

# Ver las primeras filas filtradas
df_animales.head(10)

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion,causa_amenaza,tipo_habitat
0,Myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
1,Alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
2,Amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
3,Ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
4,Ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
5,Australoheros facetus,Chanchito,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
6,Branta canadensis,Barnacla canadiense grande,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
7,Threskiornis aethiopicus,Ibis sagrado,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
8,Esox lucius,Lucio,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
9,Fundulus heteroclitus,Fúndulo,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN

In [25]:
# Eliminar invertebrados
df_animales = df_animales[df_animales['grupo'].str.lower() != 'invertebrados']

# Ver resultado
df_animales['grupo'].value_counts()

grupo
plantas no vasculares    1196
peces                    1165
aves                      642
ascidios                  269
mamíferos                 158
reptiles                  107
no especificado            97
anfibios                   38
Name: count, dtype: int64

In [26]:
df_animales

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion,causa_amenaza,tipo_habitat
0,Myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
1,Alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
2,Amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
3,Ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
4,Ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3667,Thamnobryum rudolphianum,Desconocido,no especificado,No especificado,PT,EN,NaN,NaN,NaN
3668,Graphania granti,Owlet moth,no especificado,No especificado,PT,EN,NaN,NaN,NaN
3669,Fissidens nobreganus,Desconocido,no especificado,No especificado,PT,EN,NaN,NaN,NaN
3670,Mesiotelus maderianus,Desconocido,no especificado,No especificado,PT,EN,NaN,NaN,NaN
3671,Trechus picoensis,Cave ground-beetle,no especificado,No especificado,PT,EN,NaN,NaN,NaN

In [27]:
# Número total de filas
total_filas = len(df_animales)

# Número de nombres científicos únicos
total_unicos = df_animales['nombre_cientifico'].nunique()

print(f"Total de filas: {total_filas}")
print(f"Nombres científicos únicos: {total_unicos}")

# Si hay duplicados
if total_filas > total_unicos:
    print(f"Hay {total_filas - total_unicos} filas duplicadas por nombre científico.")
else:
    print("No hay duplicados en la columna 'nombre_cientifico'.")

Total de filas: 3672
Nombres científicos únicos: 3672
No hay duplicados en la columna 'nombre_cientifico'.

In [28]:
# Mantener solo la primera aparición de cada nombre científico
df_animales = df_animales.drop_duplicates(subset=['nombre_cientifico'], keep='first')

print(f"Filas después de eliminar duplicados: {len(df_animales)}")

Filas después de eliminar duplicados: 3672

In [29]:
print(df.columns.tolist())

['nombre_cientifico', 'nombre_comun', 'grupo', 'habitat', 'pais', 'categoria_amenaza', 'estado_conservacion', 'causa_amenaza', 'tipo_habitat']

In [30]:
df_animales

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion,causa_amenaza,tipo_habitat
0,Myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
1,Alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
2,Amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
3,Ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
4,Ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3667,Thamnobryum rudolphianum,Desconocido,no especificado,No especificado,PT,EN,NaN,NaN,NaN
3668,Graphania granti,Owlet moth,no especificado,No especificado,PT,EN,NaN,NaN,NaN
3669,Fissidens nobreganus,Desconocido,no especificado,No especificado,PT,EN,NaN,NaN,NaN
3670,Mesiotelus maderianus,Desconocido,no especificado,No especificado,PT,EN,NaN,NaN,NaN
3671,Trechus picoensis,Cave ground-beetle,no especificado,No especificado,PT,EN,NaN,NaN,NaN

In [38]:
pip install odfpy

Collecting odfpy
  Downloading odfpy-1.4.1.tar.gz (717 kB)
     ---------------------------------------- 0.0/717.0 kB ? eta -:--:--
     -------------- ------------------------- 262.1/717.0 kB ? eta -:--:--
     ---------------------------------------- 717.0/717.0 kB 1.9 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: defusedxml in c:\users\cex-laguna\appdata\local\programs\python\python313\lib\site-packages (from odfpy) (0.7.1)
Building wheels for collected packages: odfpy
  Building wheel for odfpy (pyproject.toml): started
  Building wheel for odfpy (pyproject.toml): finished with status 'done'
  Created wheel for odfpy: filename=odfpy-1.4.1-py2.py3-none-any.whl size=137565 sha256=56063a7642fcd047dc8a33c510514e268af1e61e6a3ff6bfc12e3169d6b78582
  Stored in directory: c:\users\cex-laguna\appdata\local\pip\cache\wheels\8e\cd\9f\979443982946991080916064e4c049b91941be1800825ff74b
Successfully built odfpy
Installing collected packages: odfpy
Successfully installed odfpy-1.4.1
Note: you may need to restart the kernel to use updated packages.

In [69]:
import pandas as pd

# Leer ODS usando la primera fila como header
df_boe = pd.read_excel('boe-animales-conservacion.ods', engine='odf', header=0)

# Ver las primeras filas
print(df_boe.head())
print(df_boe.columns.tolist())

          Unnamed: 0    Unnamed: 1          Unnamed: 2              Unnamed: 3
0  Nombre científico  Nombre común  Población referida  Categoría del Catálogo
1                NaN           NaN                 NaN                     NaN
2                NaN           NaN                 NaN                     NaN
3                NaN           NaN                 NaN                     NaN
4                NaN           NaN                 NaN                     NaN
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

In [73]:
df_boe

,unnamed:_0,unnamed:_1,unnamed:_2,unnamed:_3
0,Nombre científico,Nombre común,Población referida,Categoría del Catálogo
1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN
...,...,...,...,...
1331,Hyperoodon ampulatus,Zifio calderón septentrional,NaN,NaN
1332,Mesoplodon densirostris,Zifio de Blainville,NaN,NaN
1333,Mesoplodon europaeus,Zifio de Gervais,NaN,NaN
1334,Mesoplodon mirus,Zifio de True,NaN,NaN
1335,"Ziphius cavirostris Cuvier, 1823.","Zifio de Cuvier, Zifio común.",NaN,Vulnerable

In [77]:
# Renombrar columnas
df_boe = df_boe.rename(columns={
    'unnamed:_0': 'nombre_cientifico',
    'unnamed:_1': 'nombre_comun',
    'unnamed:_2': 'localizacion',
    'unnamed:_3': 'estado_conservacion'
})

# Normalizar columnas (opcional, para evitar espacios y mayúsculas)
df_boe.columns = df_boe.columns.str.strip().str.lower().str.replace(' ', '_')

# Verificar
print(df_boe.head())
print(df_boe.columns.tolist())

  nombre_cientifico nombre_comun localizacion estado_conservacion
0               NaN          NaN          NaN                 NaN
1               NaN          NaN          NaN                 NaN
2               NaN          NaN          NaN                 NaN
3               NaN          NaN          NaN                 NaN
4               NaN          NaN          NaN                 NaN
['nombre_cientifico', 'nombre_comun', 'localizacion', 'estado_conservacion']

In [78]:
# Eliminar la fila 0
df_boe = df_boe.drop(index=0).reset_index(drop=True)

# Verificar
print(df_boe.head())

  nombre_cientifico nombre_comun localizacion estado_conservacion
0               NaN          NaN          NaN                 NaN
1               NaN          NaN          NaN                 NaN
2               NaN          NaN          NaN                 NaN
3               NaN          NaN          NaN                 NaN
4               NaN          NaN          NaN                 NaN

In [79]:
# Eliminar filas donde todos los valores sean NaN o vacíos
df_boe = df_boe.dropna(how='all')

# Verificar cuántas filas quedaron
print("Número de filas después de limpiar:", len(df_boe))

Número de filas después de limpiar: 802

In [80]:
df_boe

,nombre_cientifico,nombre_comun,localizacion,estado_conservacion
305,Paeonia cambessedesi,NaN,NaN,NaN
306,Papaveraceae,NaN,NaN,NaN
307,Rupicapnos africana subsp. Decipiens,Conejitos,NaN,En peligro de extinción
308,Sarcocapnos baetica subsp. Baetica,Zapaticos de la Virgen,NaN,Vulnerable
309,Sarcocapnos baetica subsp. Integriflora,NaN,NaN,Vulnerable
...,...,...,...,...
1329,Hyperoodon ampulatus,Zifio calderón septentrional,NaN,NaN
1330,Mesoplodon densirostris,Zifio de Blainville,NaN,NaN
1331,Mesoplodon europaeus,Zifio de Gervais,NaN,NaN
1332,Mesoplodon mirus,Zifio de True,NaN,NaN
1333,"Ziphius cavirostris Cuvier, 1823.","Zifio de Cuvier, Zifio común.",NaN,Vulnerable

In [81]:
print(df_boe.columns.tolist())

['nombre_cientifico', 'nombre_comun', 'localizacion', 'estado_conservacion']

In [84]:
df_boe.columns = df_boe.columns.str.strip().str.lower().str.replace(' ', '_')
df_animales.columns = df_animales.columns.str.strip().str.lower().str.replace(' ', '_')

In [91]:
import pandas as pd

# Cargar ODS
df_boe = pd.read_excel('boe-animales-conservacion.ods', engine='odf', header=None)

# Eliminar filas completamente vacías
df_boe = df_boe.dropna(how='all').reset_index(drop=True)

# Asignar manualmente columnas que queremos
df_boe.columns = ['nombre_cientifico', 'nombre_comun', 'localizacion', 'estado_conservacion']

# Convertir todo a string, limpiar espacios y minúsculas
for col in df_boe.columns:
    df_boe[col] = df_boe[col].astype(str).str.strip().str.lower()

# Verificar
print(df_boe.head())
print(df_boe.columns.tolist())

                      nombre_cientifico            nombre_comun  \
0                     nombre científico            nombre común
1                  paeonia cambessedesi                     nan
2                          papaveraceae                     nan
3  rupicapnos africana subsp. decipiens               conejitos
4    sarcocapnos baetica subsp. baetica  zapaticos de la virgen

         localizacion      estado_conservacion
0  población referida   categoría del catálogo
1                 nan                      nan
2                 nan                      nan
3                 nan  en peligro de extinción
4                 nan               vulnerable
['nombre_cientifico', 'nombre_comun', 'localizacion', 'estado_conservacion']

In [92]:
# Eliminar la fila 0
df_boe = df_boe.drop(index=0).reset_index(drop=True)

# Verificar
print(df_boe.head())

                         nombre_cientifico            nombre_comun  \
0                     paeonia cambessedesi                     nan
1                             papaveraceae                     nan
2     rupicapnos africana subsp. decipiens               conejitos
3       sarcocapnos baetica subsp. baetica  zapaticos de la virgen
4  sarcocapnos baetica subsp. integriflora                     nan

  localizacion      estado_conservacion
0          nan                      nan
1          nan                      nan
2          nan  en peligro de extinción
3          nan               vulnerable
4          nan               vulnerable

In [93]:
import pandas as pd

# Crear diccionario de estado de conservación
conservacion_dict = df_boe.set_index('nombre_cientifico')['estado_conservacion'].to_dict()

# Rellenar df_animales
df_animales['estado_conservacion'] = df_animales['estado_conservacion'].fillna(
    df_animales['nombre_cientifico'].str.lower().str.strip().map(conservacion_dict)
)

In [94]:
print(df_animales.head(10))

          nombre_cientifico                nombre_comun      grupo  \
0       myiopsitta monachus           Cotorra argentina       aves
1         alburnus alburnus                     Alburno      peces
2         amandava amandava                Bengalí rojo       aves
3            ameiurus melas              Pez gato negro      peces
4         ammotragus lervia                       Arrui  mamíferos
5     australoheros facetus                   Chanchito      peces
6         branta canadensis  Barnacla canadiense grande       aves
7  threskiornis aethiopicus                Ibis sagrado       aves
8               esox lucius                       Lucio      peces
9     fundulus heteroclitus                     Fúndulo      peces

                     habitat pais categoria_amenaza estado_conservacion  \
0  Terrestre (incl. fluvial)   ES       No evaluado                 NaN
1  Terrestre (incl. fluvial)   ES       No evaluado                 NaN
2  Terrestre (incl. fluvial)   ES       No evaluado                 NaN
3  Terrestre (incl. fluvial)   ES       No evaluado                 NaN
4  Terrestre (incl. fluvial)   ES       No evaluado                 NaN
5  Terrestre (incl. fluvial)   ES       No evaluado                 NaN
6  Terrestre (incl. fluvial)   ES       No evaluado                 NaN
7  Terrestre (incl. fluvial)   ES       No evaluado                 NaN
8  Terrestre (incl. fluvial)   ES       No evaluado                 NaN
9  Terrestre (incl. fluvial)   ES       No evaluado                 NaN

  causa_amenaza tipo_habitat
0           NaN          NaN
1           NaN          NaN
2           NaN          NaN
3           NaN          NaN
4           NaN          NaN
5           NaN          NaN
6           NaN          NaN
7           NaN          NaN
8           NaN          NaN
9           NaN          NaN

In [95]:
total_filas = len(df_animales)
rellenados = df_animales['estado_conservacion'].notna().sum()
print(f"{rellenados} de {total_filas} filas tienen estado de conservación")

351 de 3672 filas tienen estado de conservación

In [96]:
especies = ['lynx pardinus', 'ursus arctos arctos']  # por ejemplo
print(df_animales[df_animales['nombre_cientifico'].isin(especies)])

    nombre_cientifico nombre_comun      grupo                    habitat pais  \
402     lynx pardinus        Lince  mamíferos  Terrestre (incl. fluvial)   ES

    categoria_amenaza estado_conservacion       causa_amenaza  \
402       No evaluado  En Peligro Crítico  Pérdida de hábitat

            tipo_habitat
402  Bosque mediterráneo

In [ ]:
df_animales

In [97]:
import pandas as pd

# Leer ODS sin encabezado automático
df_biodiv = pd.read_excel('biodiversidad-animal.ods', engine='odf', header=None)

# Eliminar filas completamente vacías
df_biodiv = df_biodiv.dropna(how='all').reset_index(drop=True)

In [98]:
df_biodiv

,0,1,2,3,4,5
0,NaN,NaN,Nombre científico,Nombre vulgar,NaN,estado_conservacion
1,NaN,NaN,Acipenser sturio,esturión,NaN,En peligro crítico
2,NaN,NaN,Anguilla anguilla,anguila,NaN,En peligro crítico
3,NaN,NaN,Atherina boyeri,pejerrey,NaN,Preocupación menor
4,NaN,NaN,Alosa alosa,sábalo,NaN,Preocupación menor
...,...,...,...,...,...,...
380,NaN,NaN,Psammodromus blanci,lagartija,NaN,No evaluada
381,NaN,NaN,Scelarcis perspicillata,lagartija de Marruecos,NaN,No amenazado
382,NaN,NaN,Timon lepidus,lagarto ocelado,NaN,Casi amenazado
383,NaN,NaN,Timon tangitanus,lagarto ocelado del Atlas,NaN,No evaluado
384,NaN,NaN,Zootoca vivipara,lagartija de turbera,NaN,Preocupación menor

In [99]:
# Eliminar columnas por índice
df_biodiv = df_biodiv.drop(columns=[0, 1, 4])

# Verificar
print(df_biodiv.head())
print(df_biodiv.columns.tolist())

                   2              3                    5
0  Nombre científico  Nombre vulgar  estado_conservacion
1   Acipenser sturio       esturión   En peligro crítico
2  Anguilla anguilla        anguila   En peligro crítico
3    Atherina boyeri       pejerrey   Preocupación menor
4        Alosa alosa         sábalo   Preocupación menor
[2, 3, 5]

In [100]:
# Renombrar columnas
df_biodiv = df_biodiv.rename(columns={
    2: 'nombre_cientifico',
    3: 'nombre_comun',
    5: 'estado_conservacion'
})

# Limpiar nombres: espacios, minúsculas y reemplazar espacios por guiones bajos
df_biodiv.columns = df_biodiv.columns.str.strip().str.lower().str.replace(' ', '_')

# Verificar
print(df_biodiv.head())
print(df_biodiv.columns.tolist())

   nombre_cientifico   nombre_comun  estado_conservacion
0  Nombre científico  Nombre vulgar  estado_conservacion
1   Acipenser sturio       esturión   En peligro crítico
2  Anguilla anguilla        anguila   En peligro crítico
3    Atherina boyeri       pejerrey   Preocupación menor
4        Alosa alosa         sábalo   Preocupación menor
['nombre_cientifico', 'nombre_comun', 'estado_conservacion']

In [101]:
# Eliminar la fila 0
df_biodiv = df_biodiv.drop(index=0).reset_index(drop=True)

# Verificar
print(df_biodiv.head())

   nombre_cientifico nombre_comun estado_conservacion
0   Acipenser sturio     esturión  En peligro crítico
1  Anguilla anguilla      anguila  En peligro crítico
2    Atherina boyeri     pejerrey  Preocupación menor
3        Alosa alosa       sábalo  Preocupación menor
4       Alosa fallax       saboga  Preocupación menor

In [102]:
# Crear un diccionario de estado de conservación a partir de df_biodiv
conservacion_dict = df_biodiv.set_index('nombre_cientifico')['estado_conservacion'].to_dict()

# Rellenar los valores faltantes en df_animales
df_animales['estado_conservacion'] = df_animales['estado_conservacion'].fillna(
    df_animales['nombre_cientifico'].str.lower().str.strip().map(conservacion_dict)
)

# Verificar algunos resultados
print(df_animales[['nombre_cientifico', 'estado_conservacion']].head(20))

             nombre_cientifico estado_conservacion
0          myiopsitta monachus                 NaN
1            alburnus alburnus                 NaN
2            amandava amandava                 NaN
3               ameiurus melas                 NaN
4            ammotragus lervia                 NaN
5        australoheros facetus                 NaN
6            branta canadensis                 NaN
7     threskiornis aethiopicus                 NaN
8                  esox lucius                 NaN
9        fundulus heteroclitus                 NaN
10          gambusia holbrooki                 NaN
11         ictalurus punctatus                 NaN
12             leiothrix lutea                 NaN
13            lepomis gibbosus                 NaN
14       micropterus salmoides                 NaN
15  misgurnus anguillicaudatus                 NaN
16            myocastor coypus                 NaN
17          ondatra zibethicus                 NaN
18          oxyura jamaicensis                 NaN
19           perca fluviatilis                 NaN

In [103]:
df_animales

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion,causa_amenaza,tipo_habitat
0,myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
1,alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
2,amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
3,ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
4,ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3667,thamnobryum rudolphianum,Desconocido,no especificado,No especificado,PT,EN,NaN,NaN,NaN
3668,graphania granti,Owlet moth,no especificado,No especificado,PT,EN,NaN,NaN,NaN
3669,fissidens nobreganus,Desconocido,no especificado,No especificado,PT,EN,NaN,NaN,NaN
3670,mesiotelus maderianus,Desconocido,no especificado,No especificado,PT,EN,NaN,NaN,NaN
3671,trechus picoensis,Cave ground-beetle,no especificado,No especificado,PT,EN,NaN,NaN,NaN

In [104]:
# Eliminar filas según el grupo
df_animales = df_animales[~df_animales['grupo'].isin(['plantas no vasculares', 'ascidios'])].reset_index(drop=True)

# Verificar
print(df_animales['grupo'].value_counts())

grupo
peces              1165
aves                642
mamíferos           158
reptiles            107
no especificado      97
anfibios             38
Name: count, dtype: int64

In [ ]:
df_animales

In [105]:
# Rellenar los valores vacíos de estado_conservacion
df_animales['estado_conservacion'] = df_animales['estado_conservacion'].fillna('No identificado')

# Verificar
print(df_animales['estado_conservacion'].value_counts())

estado_conservacion
No identificado            1862
nan                         264
vulnerable                   45
en peligro de extinción      28
Vulnerable                    3
En Peligro                    2
En Peligro Crítico            1
Casi Amenazada                1
Preocupación menor            1
Name: count, dtype: int64

In [106]:
df_animales

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion,causa_amenaza,tipo_habitat
0,myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
1,alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
2,amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
3,ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
4,ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2202,thamnobryum rudolphianum,Desconocido,no especificado,No especificado,PT,EN,No identificado,NaN,NaN
2203,graphania granti,Owlet moth,no especificado,No especificado,PT,EN,No identificado,NaN,NaN
2204,fissidens nobreganus,Desconocido,no especificado,No especificado,PT,EN,No identificado,NaN,NaN
2205,mesiotelus maderianus,Desconocido,no especificado,No especificado,PT,EN,No identificado,NaN,NaN
2206,trechus picoensis,Cave ground-beetle,no especificado,No especificado,PT,EN,No identificado,NaN,NaN

In [109]:
# Reemplazar NaN reales y también cadenas que digan "nan" o "NaN"
df_animales['estado_conservacion'] = df_animales['estado_conservacion'].replace(
    ['nan', 'NaN', 'NAN'], 'No identificado'
).fillna('No identificado')

# Verificar
print(df_animales['estado_conservacion'].unique())

['No identificado' 'vulnerable' 'en peligro de extinción' 'En Peligro'
 'Vulnerable' 'En Peligro Crítico' 'Casi Amenazada' 'Preocupación menor']

In [110]:
df_animales

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion,causa_amenaza,tipo_habitat
0,myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
1,alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
2,amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
3,ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
4,ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2202,thamnobryum rudolphianum,Desconocido,no especificado,No especificado,PT,EN,No identificado,NaN,NaN
2203,graphania granti,Owlet moth,no especificado,No especificado,PT,EN,No identificado,NaN,NaN
2204,fissidens nobreganus,Desconocido,no especificado,No especificado,PT,EN,No identificado,NaN,NaN
2205,mesiotelus maderianus,Desconocido,no especificado,No especificado,PT,EN,No identificado,NaN,NaN
2206,trechus picoensis,Cave ground-beetle,no especificado,No especificado,PT,EN,No identificado,NaN,NaN

In [31]:
# Lista de especies en peligro (nombres científicos)
especies_peligro = [
    # Mamíferos
    "lynx pardinus",
    "ursus arctos arctos",
    "mustela lutreola",
    "galemys pyrenaicus",
    "monachus monachus",
    "myotis capaccini",
    "ammotragus lervia",
    "ovis orientalis mussimon",
    
    # Aves
    "tetrao urogallus cantabricus",
    "aquila adalberti",
    "gypaetus barbatus",
    "ciconia nigra",
    "oxyura leucocephala",
    "neophron percnopterus",
    "chlamydotis undulata fuertaventurae",
    "anser brachyrhynchus",  # Cerceta pardilla (aproximación)
    
    # Reptiles y anfibios
    "vipera latasti",
    "alytes muletensis",
    "calotriton arnoldi",   # Tritón de Montseny (aproximación)
    "pelodytes punctatus",  # Sapillo balear (aproximación)
]

In [32]:
import pandas as pd

# Cargar tu dataset de 4000 especies
# df_animales = pd.read_csv("animales_filtrados.csv")  # o .xlsx
df_animales['nombre_cientifico'] = df_animales['nombre_cientifico'].str.strip().str.lower()

# Crear columna vacía si no existe
if 'estado_conservacion' not in df_animales.columns:
    df_animales['estado_conservacion'] = ""

In [33]:
df_animales['estado_conservacion'] = df_animales['nombre_cientifico'].apply(
    lambda x: "EN" if x in especies_peligro else ""
)

In [111]:
df_animales

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion,causa_amenaza,tipo_habitat
0,myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
1,alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
2,amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
3,ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
4,ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2202,thamnobryum rudolphianum,Desconocido,no especificado,No especificado,PT,EN,No identificado,NaN,NaN
2203,graphania granti,Owlet moth,no especificado,No especificado,PT,EN,No identificado,NaN,NaN
2204,fissidens nobreganus,Desconocido,no especificado,No especificado,PT,EN,No identificado,NaN,NaN
2205,mesiotelus maderianus,Desconocido,no especificado,No especificado,PT,EN,No identificado,NaN,NaN
2206,trechus picoensis,Cave ground-beetle,no especificado,No especificado,PT,EN,No identificado,NaN,NaN

In [112]:
df_animales.to_excel('df_animales_actualizado.xlsx', index=False)

In [119]:
import pandas as pd


#  Leer el archivo nuevo de amenazas (.ods)
df_amenaza = pd.read_excel('tipo-amenaza-animal.ods', engine='odf')

print(df_animales.columns)
print(df_amenaza.columns)

Index(['nombre_cientifico', 'nombre_comun', 'grupo', 'habitat', 'pais',
       'categoria_amenaza', 'estado_conservacion', 'causa_amenaza',
       'tipo_habitat'],
      dtype='object')
Index(['nombre_cientifico', 'nombre_comun', 'grupo', 'habitat', 'pais',
       'categoria_amenaza', 'estado_conservacion', 'causa_amenaza',
       'tipo_habitat'],
      dtype='object')

In [120]:
df_animales['nombre_cientifico'] = df_animales['nombre_cientifico'].str.strip().str.lower()
df_amenaza['nombre_cientifico'] = df_amenaza['nombre_cientifico'].str.strip().str.lower()

In [134]:
df_combinado = df_animales.merge(
    df_amenaza[['nombre_cientifico', 'categoria_amenaza']], 
    on='nombre_cientifico', 
    how='inner', 
    suffixes=('', '_nuevo')
)

In [135]:
df_combinado

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion,causa_amenaza,tipo_habitat,categoria_amenaza_nuevo
0,myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN,Especies invasoras
1,alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN,Contaminación/pérdida de hábitat
2,amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN,Pérdida de hábitat
3,ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN,Contaminación/especies invasoras
4,ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,No evaluado,No identificado,NaN,NaN,Caza/explotación
...,...,...,...,...,...,...,...,...,...,...
2202,thamnobryum rudolphianum,Desconocido,no especificado,No especificado,PT,EN,No identificado,NaN,NaN,Pérdida de hábitat
2203,graphania granti,Owlet moth,no especificado,No especificado,PT,EN,No identificado,NaN,NaN,Pérdida de hábitat
2204,fissidens nobreganus,Desconocido,no especificado,No especificado,PT,EN,No identificado,NaN,NaN,Pérdida de hábitat
2205,mesiotelus maderianus,Desconocido,no especificado,No especificado,PT,EN,No identificado,NaN,NaN,Pérdida de hábitat
2206,trechus picoensis,Cave ground-beetle,no especificado,No especificado,PT,EN,No identificado,NaN,NaN,Pérdida de hábitat

In [136]:
df_combinado['categoria_amenaza'] = df_combinado['categoria_amenaza_nuevo'].combine_first(
    df_combinado['categoria_amenaza']
)
df_combinado.drop(columns=['categoria_amenaza_nuevo'], inplace=True)

In [137]:
df_combinado

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion,causa_amenaza,tipo_habitat
0,myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,Especies invasoras,No identificado,NaN,NaN
1,alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,Contaminación/pérdida de hábitat,No identificado,NaN,NaN
2,amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,Pérdida de hábitat,No identificado,NaN,NaN
3,ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,Contaminación/especies invasoras,No identificado,NaN,NaN
4,ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,Caza/explotación,No identificado,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2202,thamnobryum rudolphianum,Desconocido,no especificado,No especificado,PT,Pérdida de hábitat,No identificado,NaN,NaN
2203,graphania granti,Owlet moth,no especificado,No especificado,PT,Pérdida de hábitat,No identificado,NaN,NaN
2204,fissidens nobreganus,Desconocido,no especificado,No especificado,PT,Pérdida de hábitat,No identificado,NaN,NaN
2205,mesiotelus maderianus,Desconocido,no especificado,No especificado,PT,Pérdida de hábitat,No identificado,NaN,NaN
2206,trechus picoensis,Cave ground-beetle,no especificado,No especificado,PT,Pérdida de hábitat,No identificado,NaN,NaN

In [138]:

df_combinado = df_combinado.drop(columns=['causa_amenaza', 'tipo_habitat'])

In [139]:
df_combinado

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion
0,myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,Especies invasoras,No identificado
1,alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,Contaminación/pérdida de hábitat,No identificado
2,amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,Pérdida de hábitat,No identificado
3,ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,Contaminación/especies invasoras,No identificado
4,ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,Caza/explotación,No identificado
...,...,...,...,...,...,...,...
2202,thamnobryum rudolphianum,Desconocido,no especificado,No especificado,PT,Pérdida de hábitat,No identificado
2203,graphania granti,Owlet moth,no especificado,No especificado,PT,Pérdida de hábitat,No identificado
2204,fissidens nobreganus,Desconocido,no especificado,No especificado,PT,Pérdida de hábitat,No identificado
2205,mesiotelus maderianus,Desconocido,no especificado,No especificado,PT,Pérdida de hábitat,No identificado
2206,trechus picoensis,Cave ground-beetle,no especificado,No especificado,PT,Pérdida de hábitat,No identificado

In [140]:
df_combinado = df_combinado[~df_combinado['pais'].str.contains('PT', na=False)]

In [141]:
df_combinado

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion
0,myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,Especies invasoras,No identificado
1,alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,Contaminación/pérdida de hábitat,No identificado
2,amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,Pérdida de hábitat,No identificado
3,ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,Contaminación/especies invasoras,No identificado
4,ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,Caza/explotación,No identificado
...,...,...,...,...,...,...,...
2105,alytes almogavarii,Desconocido,anfibios,Terrestre (incl. fluvial),ES,Pérdida de hábitat,No identificado
2106,podarcis lusitanicus,Desconocido,reptiles,Terrestre (incl. fluvial),ES,Pérdida de hábitat,No identificado
2107,ommatotriton ophryticus,Desconocido,anfibios,Terrestre (incl. fluvial),ES,Contaminación,No identificado
2108,anolis porcatus,Desconocido,reptiles,Terrestre (incl. fluvial),ES,Especies invasoras,No identificado
2109,saurodactylus fasciatus,Desconocido,reptiles,Terrestre (incl. fluvial),ES,Pérdida de hábitat,No identificado

In [142]:
df_combinado['nombre_comun'] = df_combinado['nombre_comun'].replace(
    "Desconocido", "Falta de información", regex=True
)

C:\Users\CeX-Laguna\AppData\Local\Temp\ipykernel_11168\3005009793.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_combinado['nombre_comun'] = df_combinado['nombre_comun'].replace(

In [143]:
df_combinado

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion
0,myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,Especies invasoras,No identificado
1,alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,Contaminación/pérdida de hábitat,No identificado
2,amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,Pérdida de hábitat,No identificado
3,ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,Contaminación/especies invasoras,No identificado
4,ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,Caza/explotación,No identificado
...,...,...,...,...,...,...,...
2105,alytes almogavarii,Falta de información,anfibios,Terrestre (incl. fluvial),ES,Pérdida de hábitat,No identificado
2106,podarcis lusitanicus,Falta de información,reptiles,Terrestre (incl. fluvial),ES,Pérdida de hábitat,No identificado
2107,ommatotriton ophryticus,Falta de información,anfibios,Terrestre (incl. fluvial),ES,Contaminación,No identificado
2108,anolis porcatus,Falta de información,reptiles,Terrestre (incl. fluvial),ES,Especies invasoras,No identificado
2109,saurodactylus fasciatus,Falta de información,reptiles,Terrestre (incl. fluvial),ES,Pérdida de hábitat,No identificado