In [94]:
import pandas as pd

# Cargar CSV
df = pd.read_csv('animales_enriquecidos.csv')

# Normalizar columnas
df.columns = df.columns.str.lower().str.replace(' ', '_')

# Ver las primeras filas
df.head(10)

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion,causa_amenaza,tipo_habitat,area_protegida,grupo_extra,dieta
0,Myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
1,Acrothamnion preissii,Desconocido,algas,Marino,ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
2,Aedes albopictus,Desconocido,invertebrados,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
3,Alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
4,Amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
5,Ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
6,Ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
7,Armadillidium vulgare,Desconocido,invertebrados,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
8,Australoheros facetus,Chanchito,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
9,Branta canadensis,Barnacla canadiense grande,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN

In [95]:
# Lista de grupos que NO son animales
no_animales = ['planta','plantas vasculares','hongos','briofitos','flora','algas','cromistas y bacterias']

# Filtrar solo animales
df_animales = df[~df['grupo'].str.lower().isin(no_animales)]

# Quitar filas sin nombre científico
df_animales = df_animales.dropna(subset=['nombre_cientifico'])

# Ver las primeras filas filtradas
df_animales.head(10)

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion,causa_amenaza,tipo_habitat,area_protegida,grupo_extra,dieta
0,Myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
2,Aedes albopictus,Desconocido,invertebrados,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
3,Alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
4,Amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
5,Ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
6,Ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
7,Armadillidium vulgare,Desconocido,invertebrados,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
8,Australoheros facetus,Chanchito,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
9,Branta canadensis,Barnacla canadiense grande,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
10,Bursaphelenchus xylophilus,Desconocido,invertebrados,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
# Eliminar invertebrados
df_animales = df_animales[df_animales['grupo'].str.lower() != 'invertebrados']

# Ver resultado
df_animales['grupo'].value_counts()

grupo
plantas no vasculares    1319
peces                    1183
aves                     1107
ascidios                  270
mamíferos                 172
no especificado           108
reptiles                  107
anfibios                   39
Name: count, dtype: int64

In [97]:
df_animales

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion,causa_amenaza,tipo_habitat,area_protegida,grupo_extra,dieta
0,Myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
3,Alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
4,Amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
5,Ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
6,Ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
51469,Rana iberica,Desconocido,no especificado,No especificado,PT,No evaluado,En Peligro,Contaminación de ríos,Ríos y arroyos,Parque Nacional Peneda-Gerês,Anfibio,Insectívoro
51470,Salmo trutta,Desconocido,no especificado,No especificado,ES,No evaluado,Preocupación menor,Sobrepesca,Ríos y lagos,Parque Nacional Picos de Europa,Pez,Omnívoro
51471,Ciconia nigra,Desconocido,no especificado,No especificado,PT,No evaluado,Vulnerable,Destrucción de humedales,Bosques y humedales,Parque Natural Montesinho,Ave,Carnívoro
51472,Vipera seoanei,Desconocido,no especificado,No especificado,ES,No evaluado,Casi Amenazada,Fragmentación de hábitat,Montañas y pastizales,Parque Natural de Somiedo,Reptil,Carnívoro
51473,Emys orbicularis,Desconocido,no especificado,No especificado,PT,No evaluado,Vulnerable,Contaminación de aguas,Ríos y lagos,Parque Nacional Doñana,Reptil,Omnívoro

In [98]:
# Número total de filas
total_filas = len(df_animales)

# Número de nombres científicos únicos
total_unicos = df_animales['nombre_cientifico'].nunique()

print(f"Total de filas: {total_filas}")
print(f"Nombres científicos únicos: {total_unicos}")

# Si hay duplicados
if total_filas > total_unicos:
    print(f"Hay {total_filas - total_unicos} filas duplicadas por nombre científico.")
else:
    print("No hay duplicados en la columna 'nombre_cientifico'.")

Total de filas: 4305
Nombres científicos únicos: 3672
Hay 633 filas duplicadas por nombre científico.

In [99]:
# Mantener solo la primera aparición de cada nombre científico
df_animales = df_animales.drop_duplicates(subset=['nombre_cientifico'], keep='first')

print(f"Filas después de eliminar duplicados: {len(df_animales)}")

Filas después de eliminar duplicados: 3672

In [100]:
print(df.columns.tolist())

['nombre_cientifico', 'nombre_comun', 'grupo', 'habitat', 'pais', 'categoria_amenaza', 'estado_conservacion', 'causa_amenaza', 'tipo_habitat', 'area_protegida', 'grupo_extra', 'dieta']

In [101]:
df_animales = df_animales.drop(columns={'grupo_extra','dieta', 'area_protegida'})

In [102]:
df_animales

,nombre_cientifico,nombre_comun,grupo,habitat,pais,categoria_amenaza,estado_conservacion,causa_amenaza,tipo_habitat
0,Myiopsitta monachus,Cotorra argentina,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
3,Alburnus alburnus,Alburno,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
4,Amandava amandava,Bengalí rojo,aves,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
5,Ameiurus melas,Pez gato negro,peces,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
6,Ammotragus lervia,Arrui,mamíferos,Terrestre (incl. fluvial),ES,No evaluado,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
51461,Thamnobryum rudolphianum,Desconocido,no especificado,No especificado,PT,EN,NaN,NaN,NaN
51462,Graphania granti,Owlet moth,no especificado,No especificado,PT,EN,NaN,NaN,NaN
51463,Fissidens nobreganus,Desconocido,no especificado,No especificado,PT,EN,NaN,NaN,NaN
51464,Mesiotelus maderianus,Desconocido,no especificado,No especificado,PT,EN,NaN,NaN,NaN
51465,Trechus picoensis,Cave ground-beetle,no especificado,No especificado,PT,EN,NaN,NaN,NaN

In [104]:
# Guardar DataFrame en Excel
df_animales.to_excel("animales_filtrados.xlsx", index=False)
print("Archivo Excel creado: 'animales_filtrados.xlsx'")

Archivo Excel creado: 'animales_filtrados.xlsx'